import { writeFile } from 'node:fs/promises';
import { demoWorkspace } from '../lib/demo.mjs';
import { FIELD_LABELS } from '../lib/import.mjs';
import { STAGES, totals } from '../lib/model.mjs';

// Stable exports for documentation and the offline worker; browser dates remain relative.
const data=demoWorkspace(new Date('2026-10-03T12:00:00-04:00'));
const keys=Object.keys(FIELD_LABELS),cell=value=>`"${String(value??'').replaceAll('"','""')}"`;
await writeFile(new URL('../test/fixtures/sponsors.csv',import.meta.url),[keys.join(','),...data.sponsors.map(s=>keys.map(k=>cell(s[k])).join(','))].join('\r\n')+'\r\n');
const leads=data.sponsors.map((s,i)=>({id:`lead-${String(i+1).padStart(3,'0')}`,company:s.company,contact:s.contact,channel:s.channel,address:s.address,ask:`$${s.amount.toLocaleString('en-US')} proposed contribution`,notes:s.notes,status:s.stage==='Qualified'?'ready':s.stage==='Negotiating'?'contract_review':s.stage.toLowerCase(),owner:s.owner,stage:s.stage,amount:s.amount,received:s.received,nextAction:s.nextAction,nextDate:s.nextDate,source:s.source,fit:s.fit,category:s.category}));
const fixture={mock:true,event:{name:data.event.name,date:data.event.date,location:data.event.location,expected_attendees:data.event.attendees,organizer:'Alex Morgan',email:'organizer@example.com',sponsor_benefits:data.event.benefits},leads,contracts:[{id:'contract-001',lead_id:'lead-002',status:'draft_pending_organizer_review',proposed_contribution:'$4,000 proposed contribution',proposed_benefits:'Mentor session and organizer-approved recruiting benefits',document:'contracts/contract-001.md',signed:false,next_action:'Organizer reviews proposed terms before sharing.'}]};
await writeFile(new URL('../../messaging-integration/demo/fixtures.json',import.meta.url),JSON.stringify(fixture,null,2)+'\n');
const summary=totals(data.sponsors);
let strategy=`# Sponsorship Relationship Strategy\n\nAmbassador coordinates events, people, and outreach: from party attendance and weddings to recruiter outreach, startup go-to-market work, and political campaigns. This demo focuses on hackathon sponsorship. Other use cases are product directions, not implemented modules in this POC.\n\nThis mock dataset contains ${leads.length} fictional prospective sponsor accounts, including committed and declined outcomes. Companies, contacts, phone numbers, relationships, payment records, and histories are invented. Example.com URLs are placeholders, not verified lead sources. Never contact these records as real prospects.\n\n## Dataset and workflow\n\nThe source of truth is web/lib/demo.mjs. Run npm run demo:export from web to regenerate the sponsor CSV, messaging fixtures, and this guide. Browser demo dates are relative to today; exported walkthrough dates use October 3, 2026 and an event on November 14, 2026. The dashboard displays current distribution by channel and stage, not historical conversion rates.\n\n`;
strategy+=`| Stage | Accounts |\n| --- | --- |\n${STAGES.map(stage=>`| ${stage} | ${leads.filter(l=>l.stage===stage).length} |`).join('\n')}\n\nMock committed funding: $${summary.committed.toLocaleString('en-US')}; received: $${summary.received.toLocaleString('en-US')}; goal: $${data.event.goal.toLocaleString('en-US')}. These figures are scenario data, not real payments.\n\n`;
strategy+=`## Relationship rules\n\nUse verified conversation history and event fit to choose an approach. Separate observations from interpretations and record confidence. Ask directly when the blocker is unclear; silence does not establish interest or rejection.\n\nFor each opportunity, record the objective, evidence, likely blocker, next question, fallback, approved limits, and follow-up date. Never invent audience numbers, competing offers, deadlines, prior promises, or authority. Do not promise exclusivity, discounts, custom benefits, or deliverables outside organizer-approved terms. Every live message requires approval of its exact draft.\n\nIdentified accounts need contact research. Qualified accounts may receive a first pitch after approval. Contacted accounts need a measured follow-up, not another initial pitch. Replied accounts need answers to specific questions. Negotiating accounts need bounded terms and organizer review. Committed accounts need fulfillment and payment tracking. Declined accounts should not receive repeated pitches. The offline worker maps only Qualified to ready and Negotiating to contract_review.\n\n## Acquiring real leads\n\nReplace placeholder sources with verified official partnership pages, previous event sponsor lists, campus/alumni introductions, relevant company student programs, and local business directories. Record the actual source URL, permission for a warm introduction, the decision owner, and an evidence-backed reason for fit. Verify email or phone before drafting; a profile phone number is not proof of ownership or permission to contact.\n\n## Fictional account strategies\n\n`;
for(const [i,s] of data.sponsors.entries())strategy+=`### ${s.company} — ${s.stage}\n\n- Contact: ${s.contact}; ${s.channel}; ${s.address}. Phone identity: ${data.users[0].phoneNumber}; email: ${data.users[0].email}.\n- Owner: ${s.owner}. Proposed contribution: $${s.amount.toLocaleString('en-US')}; received in scenario: $${s.received.toLocaleString('en-US')}.\n- Mock evidence and approach: ${s.notes}\n- Fit to verify: ${s.fit}\n- Next step: ${s.nextAction}. Follow-up: ${s.nextDate}.\n- Placeholder lead source: ${s.source}\n- Fallback: ${s.stage==='Declined'?'Pause outreach; revisit only when event timing or fit changes.':s.stage==='Committed'?'Resolve fulfillment or payment timing; do not reopen pricing without organizer review.':'Ask whether budget, timing, scope, or the decision owner is the blocker; propose a smaller approved scope only after learning the constraint.'}\n\n`;
await writeFile(new URL('../../STRATEGY.md',import.meta.url),strategy);
console.log(`Exported ${leads.length} fictional sponsors, worker fixtures, and STRATEGY.md.`);
